// TypeScript PoC: prove the @dexos/sdk surface (over the NODEJS wasm target)
// reproduces the pinned cross-language conformance vectors bit-for-bit, and that
// the pure-TS money helpers never drift from the wasm core. Every expected value
// comes from conformance/vectors.json — the single source of truth generated by
// `cargo run -p dexos-xtask -- gen-vectors`. Nothing is recomputed in JS.
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { Buffer } from "node:buffer";
import { describe, it, expect } from "vitest";

import {
  encode_get_market_request,
  ed25519_sign,
  sign_submit_order,
  amount_to_decimal,
  amount_from_decimal,
  decode_response,
  Amount,
  rawToDecimal,
  decimalToRaw,
} from "../src/index.node.js";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "../../..");
const vectors = JSON.parse(
  readFileSync(resolve(repoRoot, "conformance/vectors.json"), "utf8"),
) as Record<string, any>;

const toHex = (u8: Uint8Array): string => Buffer.from(u8).toString("hex");
const fromHex = (h: string): Uint8Array => new Uint8Array(Buffer.from(h, "hex"));

describe("frame bit-identity vs conformance/vectors.json", () => {
  it("LOGIC #1 — framed GetMarket request (types + codec + framing)", () => {
    const v = vectors.encode_get_market_request;
    const out = encode_get_market_request(
      BigInt(v.input.request_id), // u64 -> BigInt
      v.input.market_id, // u32 -> number
    );
    expect(toHex(out)).toBe(v.frame_hex);
  });

  it("LOGIC #2 — deterministic ed25519 signature (crypto)", () => {
    const v = vectors.ed25519_sign;
    const sig = ed25519_sign(
      fromHex(v.input.seed_hex),
      new TextEncoder().encode(v.input.msg_utf8),
    );
    expect(toHex(sig)).toBe(v.sig_hex);
  });

  it("LOGIC #3 — the control-signing SSoT surface (deepEqual)", () => {
    const v = vectors.signed_submit_order;
    const s = sign_submit_order(
      fromHex(vectors.seed_hex),
      BigInt(v.input.client_id),
      BigInt(v.input.nonce),
    );
    // Wire deepEqual: the whole signed-submit object must match the pinned
    // vector field-for-field. A drift in any of preimage / signature /
    // command_hash / framed_request fails here.
    expect({
      preimage_hex: toHex(s.preimage),
      signature_hex: toHex(s.signature),
      command_hash_hex: toHex(s.command_hash),
      framed_request_hex: toHex(s.framed_request),
    }).toEqual({
      preimage_hex: v.preimage_hex,
      signature_hex: v.signature_hex,
      command_hash_hex: v.command_hash_hex,
      framed_request_hex: v.framed_request_hex,
    });
    // The preimage is domain-tagged (dexos.rpc.control.v1) then postcard(payload).
    expect(s.preimage.length).toBeGreaterThan(20);
  });
});

describe("money converter — wasm core is the source of truth", () => {
  it("wasm raw <-> canonical fixed-6dp decimal both directions", () => {
    const v = vectors.amount_pin;
    expect(amount_to_decimal(v.raw)).toBe(v.decimal);
    expect(amount_from_decimal(v.decimal)).toBe(v.raw);
  });

  it("pure-TS amount.ts mirrors the wasm core exactly (deepEqual)", () => {
    const v = vectors.amount_pin;
    // Pure-TS view of the pinned money value.
    const fromRaw = Amount.fromRaw(BigInt(v.raw));
    const fromDec = Amount.fromDecimal(v.decimal);
    expect({
      raw: fromRaw.raw.toString(),
      decimal: fromRaw.toDecimal(),
    }).toEqual({ raw: v.raw, decimal: v.decimal });
    expect(fromDec.raw.toString()).toBe(v.raw);
    // The pure-TS helpers agree with the wasm core on both directions.
    expect(rawToDecimal(BigInt(v.raw))).toBe(amount_to_decimal(v.raw));
    expect(decimalToRaw(v.decimal).toString()).toBe(amount_from_decimal(v.decimal));
  });

  it("fixed-6dp edge cases match Rust format_amount", () => {
    expect(rawToDecimal(1_500_000n)).toBe("1.500000");
    expect(rawToDecimal(0n)).toBe("0.000000");
    expect(rawToDecimal(-1n)).toBe("-0.000001");
    expect(decimalToRaw("1.5")).toBe(1_500_000n);
    expect(decimalToRaw("-0.000001")).toBe(-1n);
    expect(() => decimalToRaw("1.1234567")).toThrow();
  });
});

describe("decode_response is wired to the core's total frame decoder", () => {
  it("rejects a request frame (msg_type=1, not a response)", () => {
    const requestFrame = fromHex(vectors.encode_get_market_request.frame_hex);
    expect(() => decode_response(requestFrame)).toThrow();
  });
});
