# Type Path                       Mode User  Group Age Argument
d /etc/dexos                     0750 root  dexos -   -
d /etc/dexos/tls                 0750 root  dexos -   -
d /var/lib/dexos                 0750 dexos dexos -   -
d /var/lib/dexos/data            0750 dexos dexos -   -
d /var/lib/dexos/admin           0700 root  root  -   -
d /opt/dexos                     0755 root  root  -   -
d /opt/dexos/releases            0755 root  root  -   -
