# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401


def amount_to_decimal(decimal:str) -> str:
    r"""
    Canonicalize a decimal amount string through the core's single money
    converter: parses `decimal` (max 6 fractional digits) into the `i128`
    [`Amount`](dexos_sdk_core::Amount) and re-formats it fixed-6dp, e.g.
    `"1.5"` -> `"1.500000"`. Raises `ValueError` on an invalid amount.
    """
    ...

def ed25519_sign(seed:bytes,msg:bytes) -> bytes:
    r"""
    Deterministic ed25519 signature over `msg` for the keypair derived from the
    32-byte `seed`. Raises `ValueError` if `seed` is not exactly 32 bytes.
    """
    ...

def encode_get_market_request(request_id:int,market_id:int) -> bytes:
    r"""
    Deterministic framed `GetMarket` request. Delegates entirely to the core's
    single source of truth; the python crate never re-implements framing.
    """
    ...

def sign_submit_order(seed:bytes,client_id:int,nonce:int) -> dict[str, bytes]:
    r"""
    The SSoT control-signing round-trip for a fixed `SubmitOrder`: returns a dict
    with the `preimage`, `signature`, `command_hash`, and full `framed_request`
    as `bytes`. These are exactly the values that must never drift between
    languages. Raises `ValueError` if `seed` is not 32 bytes.
    """
    ...

